#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hgtools
Version  : 8.2.0
Release  : 43
URL      : https://files.pythonhosted.org/packages/83/e8/fc576b4a1664d1f170a8251f2774dcad9d577a3cd631c9185b7ed3675159/hgtools-8.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/83/e8/fc576b4a1664d1f170a8251f2774dcad9d577a3cd631c9185b7ed3675159/hgtools-8.2.0.tar.gz
Summary  : Classes and setuptools plugin for Mercurial and Git repositories
Group    : Development/Tools
License  : MIT
Requires: hgtools-license = %{version}-%{release}
Requires: hgtools-python = %{version}-%{release}
Requires: hgtools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/hgtools.svg
:target: `PyPI link`_
.. image:: https://img.shields.io/pypi/pyversions/hgtools.svg
:target: `PyPI link`_

%package license
Summary: license components for the hgtools package.
Group: Default

%description license
license components for the hgtools package.


%package python
Summary: python components for the hgtools package.
Group: Default
Requires: hgtools-python3 = %{version}-%{release}

%description python
python components for the hgtools package.


%package python3
Summary: python3 components for the hgtools package.
Group: Default
Requires: python3-core
Provides: pypi(hgtools)

%description python3
python3 components for the hgtools package.


%prep
%setup -q -n hgtools-8.2.0
cd %{_builddir}/hgtools-8.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589219297
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hgtools
cp %{_builddir}/hgtools-8.2.0/LICENSE %{buildroot}/usr/share/package-licenses/hgtools/8e6689d37f82d5617b7f7f7232c94024d41066d1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hgtools/8e6689d37f82d5617b7f7f7232c94024d41066d1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
